### PR TITLE
fix: Breaking typo in 0005-remove-dupe-multi-user-target.patch

### PR DESCRIPTION
**Pull request by kajiya3141**
@utkarsh2102 So... I messed up the patch :frowning_face: There was a trailing "r" typo that will almost definitely break the service file as is. Do I need to create another d/changelog entry? I will if I need to and add it as an extra commit here :smile:

### CODE REVIEW

**Comment by kajiya3141** [comment]
Also, is it worth me creating a new LP bug or shall I just add the new patch there and ask for it to be sponsored, uploaded to ``lunar``, *then* SRU?

**Comment by utkarsh2102** [comment]
> So... I messed up the patch  There was a trailing "r" typo that will almost definitely break the service file as is. Do I need to create another d/changelog entry? I will if I need to and add it as an extra commit here

Yes, each upload warrants a separate d/ch entry with a new version. We cannot reuse the versions we've already used. Just like serials in the image builds.

>  Also, is it worth me creating a new LP bug or shall I just add the new patch there and ask for it to be sponsored, uploaded to lunar, then SRU?

No, we can (and should) use the same bug for tracking that. I'll mark it from "Fix released" to "New" again.

**Review by utkarsh2102 — APPROVED** [review]
Thank you. My bad, I should've spotted it. :(

**Comment by utkarsh2102** [comment]
> Yes, each upload warrants a separate d/ch entry with a new version. We cannot reuse the versions we've already used. Just like serials in the image builds.

Added a d/ch entry via fa3cfd9364118723ec0e92ab2ac526a963bf2832 and sponsored the upload.

**Pull request merged**
